---

- name: Include distribution and version specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Get service facts
  service_facts:

- name: Transfer nginx.list.j2 template to the remote location
  template:
    src: nginx.list.j2
    dest: /etc/apt/sources.list.d/nginx.list
    owner: root
    group: root
    mode: 0644

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Ensure required packages are installed
  apt:
    name: "{{ required_packages }}"
    update_cache: true
    state: present

- name: Install Nginx for Debian based OS block
  block:
    - name: Install the specified version of Nginx from nginx repo
      apt:
        name: "nginx={{ version }}"
        allow_unauthenticated: true
        state: present
      when: version != "latest"

    - name: Install the latest version of Nginx from nginx repo
      apt:
        name: nginx
        allow_unauthenticated: true
        state: present
      when: version == "latest"

- name: Ensure ufw systemd service is stopped and disabled
  service:
    name: ufw
    state: stopped
    enabled: false
  when: ansible_facts.services["ufw"] is defined