---

# TODO: Review https://github.com/nginxinc/ansible-role-nginx for improvements

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    nginx_installed: false
  when: ansible_facts.services["nginx.service"] is not defined

- name: Include distribution specific tasks
  include_tasks: "install_{{ ansible_os_family | lower }}.yml"

- name: Ensure required kernel parameters set correctly
  sysctl:
    sysctl_file: /etc/sysctl.d/99-nginx.conf
    reload: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ required_kernel_params }}"

- name: Stop firewalld if desired by user
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: not (firewalld_enabled | bool)

- name: Firewalld related block
  block:
    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true
      changed_when: false

    - name: Manage firewalld configuration
      firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ required_ports }}"
  when: (firewalld_enabled | bool)

- name: Transfer template files to the remote location
  template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src_path: nginx.conf.j2, dest_path: /etc/nginx/nginx.conf, user: root, group: root, mode: '0644'}
    - {src_path: nginx.service.j2, dest_path: /usr/lib/systemd/system/nginx.service, user: root, group: root, mode: '0644'}
  notify: start and enable nginx

- name: Include ramfs.yml conditionally
  include_tasks: ramfs.yml
  when:
    - (enable_caching | bool)
    - (enable_ramfs | bool)

- name: Include vservers.yml conditionally
  include_tasks: vservers.yml
  when: (vservers | length > 0)

- name: Set fact after installation
  set_fact:
    nginx_installed: true
