---

- name: Include version specific variables for CentOS/RHEL
  include_vars: "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    nginx_installed: false
  when: ansible_facts.services["nginx.service"] is not defined

- name: Transfer nginx repo template to the remote location
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure required packages are installed
  yum:
    name: "{{ required_packages }}"
    state: present

- name: Install the specified version of Nginx
  yum:
    name: "nginx-{{ version }}"
    enablerepo: nginx
    state: present
  when: version != "latest"

- name: Install the latest version of Nginx
  yum:
    name: nginx
    enablerepo: nginx
    state: present
  when: version == "latest"

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: true
  changed_when: false

- name: Ensure required kernel parameters set correctly
  sysctl:
    sysctl_file: /etc/sysctl.d/99-nginx.conf
    reload: true
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ required_kernel_params }}"

- name: Block for ramfs
  block:
    - name: Check if ramfs directory exists
      stat:
        path: "{{ ramfs_dir }}"
      register: ramfs_dir_stat_result

    - name: Create ramfs directory
      file:
        path: "{{ ramfs_dir }}"
        state: directory
        owner: nginx
        group: root
      when: not ramfs_dir_stat_result.stat.exists

    - name: Ensure ramfs is mounted
      mount:
        name: "{{ ramfs_dir }}"
        src: tmpfs
        fstype: tmpfs
        opts: "defaults,size={{ ramfs_size }},uid=nginx,gid=nginx"
        state: mounted
  when: (enable_caching | bool) and (enable_ramfs | bool)

- name: Ensure required ports are reachable over firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ required_ports }}"

- name: Transfer template files to the remote location
  template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - {src_path: nginx.conf.j2, dest_path: /etc/nginx/nginx.conf, user: root, group: root, mode: '0644'}
    - {src_path: nginx.service.j2, dest_path: /usr/lib/systemd/system/nginx.service, user: root, group: root, mode: '0644'}
  notify:
    - start and enable nginx service

...
