---
- name: Include version specific variables for CentOS/RHEL
  include_vars: "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"

- name: Transfer nginx repo template to the remote location
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Ensure required packages are installed
  yum:
    name: "{{ required_packages }}"
    state: present

- name: Install Nginx for CentOS/RHEL 7 block
  block:
    - name: Install the specified version of Nginx from nginx repo for CentOS/RHEL 7
      yum:
        name: "nginx-{{ version }}"
        enablerepo: nginx
        state: present
      when: version != "latest"

    - name: Install the latest version of Nginx from nginx repo for CentOS/RHEL 7
      yum:
        name: nginx
        enablerepo: nginx
        state: present
      when: version == "latest"
  when: ansible_distribution_major_version | int == 7

- name: Install Nginx for CentOS/RHEL 8 block
  block:
    - name: Install the specified version of Nginx from nginx repo for CentOS/RHEL 8
      yum:
        name: "nginx-{{ version }}"
        enablerepo: nginx
        disablerepo: AppStream
        state: present
      when: version != "latest"

    - name: Install the latest version of Nginx from nginx repo for CentOS/RHEL 8
      yum:
        name: nginx
        enablerepo: nginx
        disablerepo: AppStream
        state: present
      when: version == "latest"
  when: ansible_distribution_major_version | int == 8

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
