---
- name: Include install.yml file conditionally
  include_tasks: install_main.yml
  when: (install_nginx | bool)

- name: Include uninstall.yml file conditionally
  include_tasks: uninstall_main.yml
  when: not (install_nginx | bool)
