---

- name: Get service facts
  service_facts:

- name: Check if Nginx is installed
  set_fact:
    nginx_installed: true
  when: ansible_facts.services["nginx.service"] is defined

- name: Remove Nginx block
  block:
    - name: Ensure nginx service is stopped and disabled
      service:
        name: nginx
        state: stopped
        enabled: false

    - name: Firewalld related block while uninstalling
      block:
        - name: Ensure firewalld configuration is reverted
          firewalld:
            port: "{{ item }}"
            permanent: true
            immediate: true
            state: disabled
          loop: "{{ required_ports }}"

        - name: Ensure firewalld configuration is reverted when vservers present
          firewalld:
            port: "{{ item.port }}"
            permanent: true
            immediate: true
            state: disabled
          loop: "{{ vservers }}"
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Include distribution specific tasks
      include_tasks: "uninstall_{{ ansible_os_family | lower }}.yml"

    - name: Ramfs related uninstallation block
      block:
        - name: Unmount ramfs directory
          mount:
            path: "{{ ramfs_dir }}"
            state: unmounted

        - name: Remove ramfs directory
          file:
            path: "{{ ramfs_dir }}"
            state: absent
      when: (enable_caching | bool) and (enable_ramfs | bool)

    - name: Set fact after uninstallation
      set_fact:
        nginx_installed: false
  rescue:
    - name: Print error message and fail
      fail:
        msg: "Got an error inside block, try to rerun tasks with -v option"
  when: ansible_facts.services["nginx.service"] is defined
