---
- name: Remove nginx package
  apt:
    name: nginx
    state: absent
    purge: true

- name: Remove transferred files and created directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/nginx.list
    - /etc/nginx
